### ISSUE TITLE
Include file 'sec_api/sys/timeb_s.h' not found on Windows

### ISSUE THREAD

**Issue by jaromil** [dyne/cjit#48]
![image](https://github.com/user-attachments/assets/19806d5f-0579-488b-93a6-f3a7acdbdf0a)

This is due to a subdir going further down one level, and not being included in our header embed script.

@matteo-cristino tagging you here in case you can give a hand?

**Comment by matteo-cristino** [comment]
For sure, I did that part! I will look at it

**Comment by matteo-cristino** [comment]
The header has been included in #56 as a quick fix. If that is ok, I would close this issue with that and maybe open a new `enhancement` issue for TinyUntar
