### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by hrieke** [dyne/cjit#55]
Hi,

So the license in the majority of files in https://github.com/dyne/cjit/blob/main/src/ 
is the  GNU Affero General Public License, which is not the license you state in the readme.

Please update one or the other.  Thanks!

**Comment by jaromil** [comment]
I see the discrepancy! someone else mentioned it before to me but I did not understand what was it.

Yes we need to switch that to GPLv3+ as stated in the documentation and REUSE.toml

My bad: I was lazy enough to cut&paste the license header from another project...

**Comment by hrieke** [comment]
Awesome, happy that it's a straight forward correction for you.
Hazards of Copy / Pasta, know it well.

**Comment by jaromil** [comment]
Meanwhile I've included a license clarification in the new FAQ here https://dyne.org/docs/cjit/faq/
