### ISSUE TITLE
Detect UTF-16 files and error out before execution

### ISSUE THREAD

**Issue by jaromil** [dyne/cjit#61]
The TinyCC parser cannot process UTF-16 encoded files and doesn't give a proper error about it.

We need to detect file encoding before passing it to tcc and print out an appropriate error or, maybe, convert them to UTF-8.

Detecting UTF-16 encoding in C can be done using a few different methods. Here are some common approaches:

1. Byte Order Mark (BOM): Check for the presence of a BOM at the start of the file. UTF-16 Little Endian files start with `0xFF 0xFE`, and UTF-16 Big Endian files start with `0xFE 0xFF`.
2. Null Distribution: UTF-16 encoded text often has a high frequency of null bytes (0x00) in the data. You can scan the file for these patterns.
3. Newline Characters: Look for common newline characters (0x0A and 0x0D) in UTF-16 encoding. Depending on the endianness, these will appear as `0x0A 0x00` or `0x00 0x0A`.

Reference code for BOM detection:

```c
int detect_utf16_bom(const char *filename) {
    FILE *file = fopen(filename, "rb");
    if (!file) return -1;

    uint8_t bom[2];
    fread(bom, 1, 2, file);
    fclose(file);

    if (bom[0] == 0xFF && bom[1] == 0xFE) {
        return 1; // UTF-16 LE
    } else if (bom[0] == 0xFE && bom[1] == 0xFF) {
        return 2; // UTF-16 BE
    } else {
        return 0; // No BOM
    }
}

int main() {
    const char *filename = "example.txt";
    int result = detect_utf16_bom(filename);
    if (result == 1) {
        printf("File is UTF-16 Little Endian\n");
    } else if (result == 2) {
        printf("File is UTF-16 Big Endian\n");
    } else {
        printf("File is not UTF-16 or has no BOM\n");
    }
    return 0;
}
```

**Comment by matteo-cristino** [comment]
Not only utf16, but also utf8 with bom makes it fail.

**Comment by jaromil** [comment]
This is now fixed (correct error on BOM) and also the tutorial has download commands that encode to ASCII.

Many thanks!
