### ISSUE TITLE
Adding additional options to tinycc `configure` command line

### ISSUE THREAD

**Issue by larsks** [dyne/cjit#62]
I'm building cjit on Fedora 40, which means that with the default build, if I try to run simple code like this...

```
#include <stdlib.h>
#include <stdio.h>

int main(int argc, char *argv[])
{
  printf("hello world\n");
  return EXIT_SUCCESS;
}
```

...it fails like this:

```
CJIT v0.8.12 by Dyne.org
Source code:
+ example.c
tcc: error: mprotect failed (did you mean to configure --with-selinux?)
TCC symbol relocation error (some library missing?)
```

The solution is to add `--with-selinux` to the tinycc configure command line, but the obvious solution doesn't work. Running `make linux-86` without any additional arguments results in:

```
cd lib/tinycc && ./configure --cc=gcc --extra-cflags="-O2 -fomit-frame-pointer -fstack-protector-all -D_FORTIFY_SOURCE=2 -fno-strict-overflow -Isrc -Ilib/tinycc -DLIBC_GNU -D_GNU_SOURCE -DKILO_SUPPORTED" --extra-ldflags="" --with-libgcc
```

You might think you could do this:

```
make linux-x86 tinycc_config=--with-selinux
```

But that results in:

```
cd lib/tinycc && ./configure --with-selinux
```

The only solution is to edit `build/linux.mk`.

- It should be easier to add `configure` options from the `make` command line.
- It would be nice if this was requirement was autodetected so that `make linux-x86` would Just Work.

**Comment by jaromil** [comment]
Thanks! I never had the chance to test it on Fedora
