### ISSUE TITLE
Run in quiet mode by default when passed a file on the command line

### ISSUE THREAD

**Issue by larsks** [dyne/cjit#65]
In order to make cjit more useful for scripting, it should not produce extraneous output when provided a file on the command line. That is, given code like this in `example.c`:

```
#include <stdlib.h>
#include <stdio.h>

int main(int argc, char *argv[])
{
  printf("hello world\n");
  return EXIT_SUCCESS;
}
```

Running:

```
cjit example.c
```

Should produce only:

```
hello world
```

Rather than:

```
CJIT v0.8.12 by Dyne.org
Source code:
+ example.c
hello world
```

The additional output should only be produced when running in interactive mode on a terminal (i.e., when `isatty(STDOUT_FILENO)` is true).

**Comment by jaromil** [comment]
I agree, let me know if you need help with the PR. I've merged your other ones, great to have you on board!
